### PR TITLE
blktests: cut script and zram based runner

### PR DESCRIPTION
**Pull request by ddiss**

### CODE REVIEW

**Comment by ddiss** [comment]
The generated blktests VM initramfs image is ~29M (with vim and a few other debugging tools).

The tests seem to run fine, but I see one failure when running atop a vanilla 4.12.0-rc2 kernel:
```/dev/zram0 provisioned and ready for /blktests/check
block/002 (remove a device while running blktrace)          
    runtime    ...
[    3.821437] run blktests block/002 at 2017-05-22 17:10:58
[    3.822663] random: mktemp: uninitialized urandom read (3 bytes read)
[    3.826965] scsi host0: scsi_debug: version 1.86 [20160430]
[    3.826965]   dev_size_mb=8, opts=0x0, submit_queues=1, statistics=0
[    3.829986] scsi 0:0:0:0: Direct-Access     Linux    scsi_debug       0186 PQ: 0 ANSI: 7
[    3.860780] sd 0:0:0:0: Attached scsi generic sg0 type 0
[    3.872675] sd 0:0:0:0: [sda] 16384 512-byte logical blocks: (8.39 MB/8.00 MiB)
[    3.880548] sd 0:0:0:0: [sda] Write Protect is off
[    3.892696] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, supports DPO and FUA
block/002 (remove a device while running blktrace)           [failed]
    runtime    ...  0.781s [sda] Synchronizing SCSI cache
    --- tests/block/002.out     2017-05-22 15:42:14.000000000 +0000
    +++ results/nodev/block/002.out.bad 2017-05-22 17:10:59.569331436 +0000
    @@ -1,2 +1,3 @@
     Running block/002
    +debugfs directory leaked
     Test complete
rapido1:/blktests#
```

Would be good to get some feedback from @osandov if possible.

**Comment by ddiss** [comment]
> Looks good to me, will test tomorrow and then​ merge

Thanks - I've pushed one extra commit which adds support for Ceph RBD as a blktests target.

**Comment by osandov** [comment]
@ddiss weird, is it failing for you consistently? If you run `./check block/002` and then `lsscsi; ls /sys/kernel/debug/block`, what's the output? And what do you have for `CONFIG_BLK_DEV_IO_TRACE` and `CONFIG_BLK_DEBUG_FS`?

**Comment by ddiss** [comment]
@osandov the test fails consistently.
Running with what (I hope) is a a simplified test-case:
```
+ eval 'lsscsi; ls /sys/kernel/debug/block; modprobe scsi_debug; lsscsi; ls /sys/kernel/debug/block; modprobe -r scsi_debug; lsscsi; ls /sys/kernel/debug/block'
++ lsscsi
++ ls /sys/kernel/debug/block
ram0  ram1  ram10  ram11  ram12  ram13  ram14  ram15  ram2  ram3  ram4  ram5  ram6  ram7  ram8  ram9  zram0
++ modprobe scsi_debug
[    3.453902] scsi host0: scsi_debug: version 1.86 [20160430]
[    3.453902]   dev_size_mb=8, opts=0x0, submit_queues=1, statistics=0
[    3.455633] scsi 0:0:0:0: Direct-Access     Linux    scsi_debug       0186 PQ: 0 ANSI: 7
[    3.495941] sd 0:0:0:0: Attached scsi generic sg0 type 0
[    3.507908] sd 0:0:0:0: [sda] 16384 512-byte logical blocks: (8.39 MB/8.00 MiB)
[    3.515725] sd 0:0:0:0: [sda] Write Protect is off
[    3.531739] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, supports DPO and FUA
[    3.691728] sd 0:0:0:0: [sda] Attached SCSI disk
++ lsscsi
[0:0:0:0]    disk    Linux    scsi_debug       0186  /dev/sda 
++ ls /sys/kernel/debug/block
ram0  ram1  ram10  ram11  ram12  ram13  ram14  ram15  ram2  ram3  ram4  ram5  ram6  ram7  ram8  ram9  sda  zram0
++ modprobe -r scsi_debug
[    3.712329] sd 0:0:0:0: [sda] Synchronizing SCSI cache
++ lsscsi
++ ls /sys/kernel/debug/block
ram0  ram1  ram10  ram11  ram12  ram13  ram14  ram15  ram2  ram3  ram4  ram5  ram6  ram7  ram8  ram9  sda  zram0
```

The kernel config is available in this repo:
https://raw.githubusercontent.com/ddiss/rapido/pr_blktests_zram/kernel/vanilla_config

CONFIG_BLK_DEBUG_FS=y and CONFIG_BLK_DEV_IO_TRACE is unset, but I've also tried it with CONFIG_BLK_DEV_IO_TRACE enabled. I take it I'm just missing some kind of SCSI hot-plug kconfig parameter?

**Comment by osandov** [comment]
Oh, you have CONFIG_SCSI_MQ_DEFAULT unset. Bart just sent a patch for this case: http://marc.info/?l=linux-block&m=149575554214132&w=2. Could you try that out?

**Comment by ddiss** [comment]
@osandov thanks for the follow up.
I've tried Bart's patch with and without CONFIG_SCSI_MQ_DEFAULT=y configured, but still see the same block/002 error.
This can be reproduced with:
- clone this repo and checkout the pr_vm_metadata_as_xattr branch
- cp rapido.conf.example rapido.conf
  - set KERNEL_SRC, KERNEL_INSTALL_MOD_PATH and BLKTESTS_SRC accordingly
  - set BLKTESTS_AUTORUN_CMD="./check block/002"
- run ./cut_blktests_zram.sh
  - dracut will be called to generate your VM image at initrds/myinitrd
- run ./vm.sh

**Pull request merged**
